[options]
; This is the password that allows database operations:
; admin_passwd = postgres
db_host = postgres
db_port = 8080
db_user = postgres
db_password = postgres
;addons_path = /usr/lib/python3/dist-packages/odoo/addons
default_productivity_apps = True
